[keyboard]
name = "RELIC"
product_name = "RELIC"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "manni"
board = "XIAO BLE"

[layout]
rows = 4
cols = 10
layers = 8
keymap = [
    [
        ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
        ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
        ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
        ["_", "_", "C", "D", "E", "F", "G", "H", "_", "_"],
    ]
]

[split]
connection = "ble"

# Split central
[split.central]

rows = 4
cols = 5
row_offset = 0
col_offset = 0

[split.central.matrix]
matrix_type = "normal"
input_pins = ["P0_02", "P0_03", "P0_28", "P0_29", "P0_04"]
output_pins = ["P1_15", "P1_14", "P1_13", "P1_12"]

# Peripheral 0
[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 5

# Peripheral 0's matrix definition
[split.peripheral.matrix]
matrix_type = "normal"
input_pins = ["P0_02", "P0_03", "P0_28", "P0_29", "P0_04"]
output_pins = ["P1_15", "P1_14", "P1_13", "P1_12"]

[ble]
enabled = true
